// <auto-generated /> — produced by MeepleLedger.Seeder. Do not edit by hand; re-emit instead.
// to re-build: dotnet run -project MeepleLedger.Seeder -- emit
using MeepleLedger.Domain;

namespace MeepleLedger.Data;

public static class CollectionSeed
{
    public static List<OwnedGame> Build(GameCatalog catalog) =>
    [
        new OwnedGame { Game = Find(catalog, "Ark Nova"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Bomb Busters"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Camel Up (Second Edition)"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Castle Combo"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "The Crew: Mission Deep Sea"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Decrypto"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Everdell"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Faraway"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Flip 7"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Forest Shuffle"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "The Fox in the Forest"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Gloomhaven"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Gloomhaven: Jaws of the Lion"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Harmonies"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Hot Streak"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Kutná Hora: The City of Silver"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Lost Ruins of Arnak"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Nemesis"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Pax Pamir: Second Edition"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Rising Sun"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Root"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "SCOUT"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Sea Salt & Paper"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Sky Team"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Slay the Spire: The Board Game"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Spirit Island"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Spots"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
        new OwnedGame { Game = Find(catalog, "Wingspan"), DateAcquired = new DateTime(2026, 8, 11), Condition = Condition.Good, Notes = "..." },
    ];

    private static Game Find(GameCatalog catalog, string name) =>
        catalog.Games.First(g => g.Name == name);
}